CREATE TABLE ACCOUNT_DETAILS(
ID INT PRIMARY KEY,
ACCOUNT_NUMBER NUMBER (6),
BALANCE NUMBER (20,6),
CREATED_BY VARCHAR(20),
CREATED_TIMESTAMP DATE
);

CREATE TABLE ACCOUNT_TRANSACTION(
ID INT PRIMARY KEY
ACCOUNT_NUMBER NUMBER(6),
TRANSACTION_AMOUNT NUMBER(20, 6),
CREATED_BY VARCHAR(20),
CREATED_TIMESTAMP DATE,
TRANSACTION_TYPE VARCHAR(10)
);